[project]
name = "lr-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "notebook>=7.3.2",
    "pandas>=2.2.3",
    "pymorphy3>=2.0.3",
    "seaborn>=0.13.2",
]
