[project]
name = "lr-1"
version = "0.1.0"
description = "Laboratory work №1"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nltk>=3.9.1",
    "notebook>=7.3.2",
    "seaborn>=0.13.2",
]
